/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.pb.Ack', null, global);
goog.exportSymbol('proto.pb.CloseRequest', null, global);
goog.exportSymbol('proto.pb.CloseResponse', null, global);
goog.exportSymbol('proto.pb.ConnectRequest', null, global);
goog.exportSymbol('proto.pb.ConnectResponse', null, global);
goog.exportSymbol('proto.pb.MsgProto', null, global);
goog.exportSymbol('proto.pb.PubAck', null, global);
goog.exportSymbol('proto.pb.PubMsg', null, global);
goog.exportSymbol('proto.pb.StartPosition', null, global);
goog.exportSymbol('proto.pb.SubscriptionRequest', null, global);
goog.exportSymbol('proto.pb.SubscriptionResponse', null, global);
goog.exportSymbol('proto.pb.UnsubscribeRequest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.PubMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.PubMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.PubMsg.displayName = 'proto.pb.PubMsg';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.PubMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.PubMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.PubMsg} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.PubMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientId: msg.getClientId(),
    guid: msg.getGuid(),
    subject: msg.getSubject(),
    reply: msg.getReply(),
    data: msg.getData_asB64(),
    sha256: msg.getSha256_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.PubMsg}
 */
proto.pb.PubMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.PubMsg;
  return proto.pb.PubMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.PubMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.PubMsg}
 */
proto.pb.PubMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setReply(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 10:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSha256(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.PubMsg} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.PubMsg.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.PubMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.PubMsg.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getClientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getGuid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getSubject();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getReply();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = this.getSha256_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      10,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.PubMsg} The clone.
 */
proto.pb.PubMsg.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.PubMsg} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string client_id = 1;
 * @return {string}
 */
proto.pb.PubMsg.prototype.getClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.pb.PubMsg.prototype.setClientId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string guid = 2;
 * @return {string}
 */
proto.pb.PubMsg.prototype.getGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.pb.PubMsg.prototype.setGuid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string subject = 3;
 * @return {string}
 */
proto.pb.PubMsg.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.pb.PubMsg.prototype.setSubject = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string reply = 4;
 * @return {string}
 */
proto.pb.PubMsg.prototype.getReply = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.pb.PubMsg.prototype.setReply = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional bytes data = 5;
 * @return {!(string|Uint8Array)}
 */
proto.pb.PubMsg.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/**
 * optional bytes data = 5;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.pb.PubMsg.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.pb.PubMsg.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/** @param {!(string|Uint8Array)} value  */
proto.pb.PubMsg.prototype.setData = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional bytes sha256 = 10;
 * @return {!(string|Uint8Array)}
 */
proto.pb.PubMsg.prototype.getSha256 = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldProto3(this, 10, ""));
};


/**
 * optional bytes sha256 = 10;
 * This is a type-conversion wrapper around `getSha256()`
 * @return {string}
 */
proto.pb.PubMsg.prototype.getSha256_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSha256()));
};


/**
 * optional bytes sha256 = 10;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSha256()`
 * @return {!Uint8Array}
 */
proto.pb.PubMsg.prototype.getSha256_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSha256()));
};


/** @param {!(string|Uint8Array)} value  */
proto.pb.PubMsg.prototype.setSha256 = function(value) {
  jspb.Message.setField(this, 10, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.PubAck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.PubAck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.PubAck.displayName = 'proto.pb.PubAck';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.PubAck.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.PubAck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.PubAck} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.PubAck.toObject = function(includeInstance, msg) {
  var f, obj = {
    guid: msg.getGuid(),
    error: msg.getError()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.PubAck}
 */
proto.pb.PubAck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.PubAck;
  return proto.pb.PubAck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.PubAck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.PubAck}
 */
proto.pb.PubAck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.PubAck} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.PubAck.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.PubAck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.PubAck.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getGuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getError();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.PubAck} The clone.
 */
proto.pb.PubAck.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.PubAck} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string guid = 1;
 * @return {string}
 */
proto.pb.PubAck.prototype.getGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.pb.PubAck.prototype.setGuid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string error = 2;
 * @return {string}
 */
proto.pb.PubAck.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.pb.PubAck.prototype.setError = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.MsgProto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.MsgProto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.MsgProto.displayName = 'proto.pb.MsgProto';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.MsgProto.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.MsgProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.MsgProto} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.MsgProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    sequence: msg.getSequence(),
    subject: msg.getSubject(),
    reply: msg.getReply(),
    data: msg.getData_asB64(),
    timestamp: msg.getTimestamp(),
    redelivered: msg.getRedelivered(),
    crc32: msg.getCrc32()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.MsgProto}
 */
proto.pb.MsgProto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.MsgProto;
  return proto.pb.MsgProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.MsgProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.MsgProto}
 */
proto.pb.MsgProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSequence(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setReply(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRedelivered(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCrc32(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.MsgProto} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.MsgProto.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.MsgProto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.MsgProto.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getSequence();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = this.getSubject();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getReply();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = this.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = this.getRedelivered();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = this.getCrc32();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.MsgProto} The clone.
 */
proto.pb.MsgProto.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.MsgProto} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional uint64 sequence = 1;
 * @return {number}
 */
proto.pb.MsgProto.prototype.getSequence = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.pb.MsgProto.prototype.setSequence = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string subject = 2;
 * @return {string}
 */
proto.pb.MsgProto.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.pb.MsgProto.prototype.setSubject = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string reply = 3;
 * @return {string}
 */
proto.pb.MsgProto.prototype.getReply = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.pb.MsgProto.prototype.setReply = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional bytes data = 4;
 * @return {!(string|Uint8Array)}
 */
proto.pb.MsgProto.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/**
 * optional bytes data = 4;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.pb.MsgProto.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.pb.MsgProto.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/** @param {!(string|Uint8Array)} value  */
proto.pb.MsgProto.prototype.setData = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional int64 timestamp = 5;
 * @return {number}
 */
proto.pb.MsgProto.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 5, 0));
};


/** @param {number} value  */
proto.pb.MsgProto.prototype.setTimestamp = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional bool redelivered = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.pb.MsgProto.prototype.getRedelivered = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 6, false));
};


/** @param {boolean} value  */
proto.pb.MsgProto.prototype.setRedelivered = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional uint32 CRC32 = 10;
 * @return {number}
 */
proto.pb.MsgProto.prototype.getCrc32 = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 10, 0));
};


/** @param {number} value  */
proto.pb.MsgProto.prototype.setCrc32 = function(value) {
  jspb.Message.setField(this, 10, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.Ack = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.Ack, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.Ack.displayName = 'proto.pb.Ack';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.Ack.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.Ack.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.Ack} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.Ack.toObject = function(includeInstance, msg) {
  var f, obj = {
    subject: msg.getSubject(),
    sequence: msg.getSequence()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.Ack}
 */
proto.pb.Ack.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.Ack;
  return proto.pb.Ack.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.Ack} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.Ack}
 */
proto.pb.Ack.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSequence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.Ack} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.Ack.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.Ack.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.Ack.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getSubject();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getSequence();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.Ack} The clone.
 */
proto.pb.Ack.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.Ack} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string subject = 1;
 * @return {string}
 */
proto.pb.Ack.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.pb.Ack.prototype.setSubject = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint64 sequence = 2;
 * @return {number}
 */
proto.pb.Ack.prototype.getSequence = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.pb.Ack.prototype.setSequence = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.ConnectRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.ConnectRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.ConnectRequest.displayName = 'proto.pb.ConnectRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.ConnectRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.ConnectRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.ConnectRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.ConnectRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientId: msg.getClientId(),
    heartbeatInbox: msg.getHeartbeatInbox()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.ConnectRequest}
 */
proto.pb.ConnectRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.ConnectRequest;
  return proto.pb.ConnectRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.ConnectRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.ConnectRequest}
 */
proto.pb.ConnectRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setHeartbeatInbox(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.ConnectRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.ConnectRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.ConnectRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.ConnectRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getClientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getHeartbeatInbox();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.ConnectRequest} The clone.
 */
proto.pb.ConnectRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.ConnectRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string client_id = 1;
 * @return {string}
 */
proto.pb.ConnectRequest.prototype.getClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.pb.ConnectRequest.prototype.setClientId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string heartbeat_inbox = 2;
 * @return {string}
 */
proto.pb.ConnectRequest.prototype.getHeartbeatInbox = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.pb.ConnectRequest.prototype.setHeartbeatInbox = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.ConnectResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.ConnectResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.ConnectResponse.displayName = 'proto.pb.ConnectResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.ConnectResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.ConnectResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.ConnectResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.ConnectResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    pubPrefix: msg.getPubPrefix(),
    subRequests: msg.getSubRequests(),
    unsubRequests: msg.getUnsubRequests(),
    closeRequests: msg.getCloseRequests(),
    error: msg.getError(),
    subCloseRequests: msg.getSubCloseRequests(),
    publicKey: msg.getPublicKey()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.ConnectResponse}
 */
proto.pb.ConnectResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.ConnectResponse;
  return proto.pb.ConnectResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.ConnectResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.ConnectResponse}
 */
proto.pb.ConnectResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPubPrefix(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubRequests(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUnsubRequests(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCloseRequests(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubCloseRequests(value);
      break;
    case 100:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublicKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.ConnectResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.ConnectResponse.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.ConnectResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.ConnectResponse.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getPubPrefix();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getSubRequests();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getUnsubRequests();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getCloseRequests();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getError();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = this.getSubCloseRequests();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = this.getPublicKey();
  if (f.length > 0) {
    writer.writeString(
      100,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.ConnectResponse} The clone.
 */
proto.pb.ConnectResponse.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.ConnectResponse} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string pub_prefix = 1;
 * @return {string}
 */
proto.pb.ConnectResponse.prototype.getPubPrefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.pb.ConnectResponse.prototype.setPubPrefix = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string sub_requests = 2;
 * @return {string}
 */
proto.pb.ConnectResponse.prototype.getSubRequests = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.pb.ConnectResponse.prototype.setSubRequests = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string unsub_requests = 3;
 * @return {string}
 */
proto.pb.ConnectResponse.prototype.getUnsubRequests = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.pb.ConnectResponse.prototype.setUnsubRequests = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string close_requests = 4;
 * @return {string}
 */
proto.pb.ConnectResponse.prototype.getCloseRequests = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.pb.ConnectResponse.prototype.setCloseRequests = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string error = 5;
 * @return {string}
 */
proto.pb.ConnectResponse.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.pb.ConnectResponse.prototype.setError = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string sub_close_requests = 6;
 * @return {string}
 */
proto.pb.ConnectResponse.prototype.getSubCloseRequests = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 6, ""));
};


/** @param {string} value  */
proto.pb.ConnectResponse.prototype.setSubCloseRequests = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string public_key = 100;
 * @return {string}
 */
proto.pb.ConnectResponse.prototype.getPublicKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 100, ""));
};


/** @param {string} value  */
proto.pb.ConnectResponse.prototype.setPublicKey = function(value) {
  jspb.Message.setField(this, 100, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SubscriptionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SubscriptionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.SubscriptionRequest.displayName = 'proto.pb.SubscriptionRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SubscriptionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SubscriptionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SubscriptionRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.SubscriptionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientId: msg.getClientId(),
    subject: msg.getSubject(),
    qGroup: msg.getQGroup(),
    inbox: msg.getInbox(),
    maxInFlight: msg.getMaxInFlight(),
    ackWaitInSecs: msg.getAckWaitInSecs(),
    durableName: msg.getDurableName(),
    startPosition: msg.getStartPosition(),
    startSequence: msg.getStartSequence(),
    startTimeDelta: msg.getStartTimeDelta()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SubscriptionRequest}
 */
proto.pb.SubscriptionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SubscriptionRequest;
  return proto.pb.SubscriptionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SubscriptionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SubscriptionRequest}
 */
proto.pb.SubscriptionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setQGroup(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setInbox(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxInFlight(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAckWaitInSecs(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDurableName(value);
      break;
    case 10:
      var value = /** @type {!proto.pb.StartPosition} */ (reader.readEnum());
      msg.setStartPosition(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setStartSequence(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartTimeDelta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.SubscriptionRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.SubscriptionRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SubscriptionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.SubscriptionRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getClientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getSubject();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getQGroup();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getInbox();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getMaxInFlight();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = this.getAckWaitInSecs();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = this.getDurableName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = this.getStartPosition();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
  f = this.getStartSequence();
  if (f !== 0) {
    writer.writeUint64(
      11,
      f
    );
  }
  f = this.getStartTimeDelta();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.SubscriptionRequest} The clone.
 */
proto.pb.SubscriptionRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.SubscriptionRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string client_id = 1;
 * @return {string}
 */
proto.pb.SubscriptionRequest.prototype.getClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.pb.SubscriptionRequest.prototype.setClientId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string subject = 2;
 * @return {string}
 */
proto.pb.SubscriptionRequest.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.pb.SubscriptionRequest.prototype.setSubject = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string q_group = 3;
 * @return {string}
 */
proto.pb.SubscriptionRequest.prototype.getQGroup = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.pb.SubscriptionRequest.prototype.setQGroup = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string inbox = 4;
 * @return {string}
 */
proto.pb.SubscriptionRequest.prototype.getInbox = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.pb.SubscriptionRequest.prototype.setInbox = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional int32 max_in_flight = 5;
 * @return {number}
 */
proto.pb.SubscriptionRequest.prototype.getMaxInFlight = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 5, 0));
};


/** @param {number} value  */
proto.pb.SubscriptionRequest.prototype.setMaxInFlight = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional int32 ack_wait_in_secs = 6;
 * @return {number}
 */
proto.pb.SubscriptionRequest.prototype.getAckWaitInSecs = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 6, 0));
};


/** @param {number} value  */
proto.pb.SubscriptionRequest.prototype.setAckWaitInSecs = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string durable_name = 7;
 * @return {string}
 */
proto.pb.SubscriptionRequest.prototype.getDurableName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 7, ""));
};


/** @param {string} value  */
proto.pb.SubscriptionRequest.prototype.setDurableName = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional StartPosition start_position = 10;
 * @return {!proto.pb.StartPosition}
 */
proto.pb.SubscriptionRequest.prototype.getStartPosition = function() {
  return /** @type {!proto.pb.StartPosition} */ (jspb.Message.getFieldProto3(this, 10, 0));
};


/** @param {!proto.pb.StartPosition} value  */
proto.pb.SubscriptionRequest.prototype.setStartPosition = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional uint64 start_sequence = 11;
 * @return {number}
 */
proto.pb.SubscriptionRequest.prototype.getStartSequence = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 11, 0));
};


/** @param {number} value  */
proto.pb.SubscriptionRequest.prototype.setStartSequence = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * optional int64 start_time_delta = 12;
 * @return {number}
 */
proto.pb.SubscriptionRequest.prototype.getStartTimeDelta = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 12, 0));
};


/** @param {number} value  */
proto.pb.SubscriptionRequest.prototype.setStartTimeDelta = function(value) {
  jspb.Message.setField(this, 12, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.SubscriptionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.SubscriptionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.SubscriptionResponse.displayName = 'proto.pb.SubscriptionResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.SubscriptionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.SubscriptionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.SubscriptionResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.SubscriptionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    ackInbox: msg.getAckInbox(),
    error: msg.getError()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.SubscriptionResponse}
 */
proto.pb.SubscriptionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.SubscriptionResponse;
  return proto.pb.SubscriptionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.SubscriptionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.SubscriptionResponse}
 */
proto.pb.SubscriptionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAckInbox(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.SubscriptionResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.SubscriptionResponse.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.SubscriptionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.SubscriptionResponse.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getAckInbox();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getError();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.SubscriptionResponse} The clone.
 */
proto.pb.SubscriptionResponse.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.SubscriptionResponse} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string ack_inbox = 2;
 * @return {string}
 */
proto.pb.SubscriptionResponse.prototype.getAckInbox = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.pb.SubscriptionResponse.prototype.setAckInbox = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string error = 3;
 * @return {string}
 */
proto.pb.SubscriptionResponse.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.pb.SubscriptionResponse.prototype.setError = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.UnsubscribeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.UnsubscribeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.UnsubscribeRequest.displayName = 'proto.pb.UnsubscribeRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.UnsubscribeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.UnsubscribeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.UnsubscribeRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.UnsubscribeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientId: msg.getClientId(),
    subject: msg.getSubject(),
    inbox: msg.getInbox(),
    durableName: msg.getDurableName()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.UnsubscribeRequest}
 */
proto.pb.UnsubscribeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.UnsubscribeRequest;
  return proto.pb.UnsubscribeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.UnsubscribeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.UnsubscribeRequest}
 */
proto.pb.UnsubscribeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setInbox(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDurableName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.UnsubscribeRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.UnsubscribeRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.UnsubscribeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.UnsubscribeRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getClientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getSubject();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getInbox();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getDurableName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.UnsubscribeRequest} The clone.
 */
proto.pb.UnsubscribeRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.UnsubscribeRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string client_id = 1;
 * @return {string}
 */
proto.pb.UnsubscribeRequest.prototype.getClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.pb.UnsubscribeRequest.prototype.setClientId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string subject = 2;
 * @return {string}
 */
proto.pb.UnsubscribeRequest.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.pb.UnsubscribeRequest.prototype.setSubject = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string inbox = 3;
 * @return {string}
 */
proto.pb.UnsubscribeRequest.prototype.getInbox = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.pb.UnsubscribeRequest.prototype.setInbox = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string durable_name = 4;
 * @return {string}
 */
proto.pb.UnsubscribeRequest.prototype.getDurableName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.pb.UnsubscribeRequest.prototype.setDurableName = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.CloseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.CloseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.CloseRequest.displayName = 'proto.pb.CloseRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.CloseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.CloseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.CloseRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.CloseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientId: msg.getClientId()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.CloseRequest}
 */
proto.pb.CloseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.CloseRequest;
  return proto.pb.CloseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.CloseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.CloseRequest}
 */
proto.pb.CloseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.CloseRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.CloseRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.CloseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.CloseRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getClientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.CloseRequest} The clone.
 */
proto.pb.CloseRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.CloseRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string client_id = 1;
 * @return {string}
 */
proto.pb.CloseRequest.prototype.getClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.pb.CloseRequest.prototype.setClientId = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.CloseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.CloseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pb.CloseResponse.displayName = 'proto.pb.CloseResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.CloseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.CloseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.CloseResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pb.CloseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: msg.getError()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.CloseResponse}
 */
proto.pb.CloseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.CloseResponse;
  return proto.pb.CloseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.CloseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.CloseResponse}
 */
proto.pb.CloseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pb.CloseResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.CloseResponse.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.CloseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pb.CloseResponse.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getError();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pb.CloseResponse} The clone.
 */
proto.pb.CloseResponse.prototype.cloneMessage = function() {
  return /** @type {!proto.pb.CloseResponse} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string error = 1;
 * @return {string}
 */
proto.pb.CloseResponse.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.pb.CloseResponse.prototype.setError = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.pb.StartPosition = {
  NEW_ONLY: 0,
  LAST_RECEIVED: 1,
  TIME_DELTA_START: 2,
  SEQUENCE_START: 3,
  FIRST: 4
};

goog.object.extend(exports, proto.pb);
